### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by nickel3d** [juergenfurrer/Ieslibrary4Blender#1]
Getting the following error out of Blender when installing the addon:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Ieslibrary4Blender-1'

**Comment by juergenfurrer** [comment]
Did you download the plugin from this link?
https://github.com/juergenfurrer/Ieslibrary4Blender/releases

Do not download the complete GIT-Repo to use in Blender.
If you do so, just use the plugin-folder "blender/Ieslibrary4Blender" [here](https://github.com/juergenfurrer/Ieslibrary4Blender/tree/main/blender/Ieslibrary4Blender)

I tried it on Blender 4.0, 4.1 and 4.2 and it worked without any problems
